### ISSUE TITLE
when I run ./pda_mnist_carlinet_untargeted_l2.sh ,the error occur

### ISSUE THREAD

**Issue by aspnetcs** [ZiangYan/pda.pytorch#1]
I0325 05:30:26.979458 11136 policy_attack.py:1433]          victim_batch_size: 50
I0325 05:30:32.276054 11136 policy_attack.py:381] Found policy keys: OrderedDict([('policy_weight_fname', 'output/policy-smtrain-inv-mnist-carlinet-untargeted-l2/2020-09-28_13-41-55-DgrgzXkj/results/model_best.pth'), ('policy_bilinear', True), ('policy_normalization_type', 'none'), ('policy_use_tanh', False), ('policy_base_width', 32), ('policy_calibrate', True), ('policy_init_std', 0.003)]), only use OrderedDict([('init_std', 0.003), ('input_size', 0), ('weight_fname', 'output/policy-smtrain-inv-mnist-carlinet-untargeted-l2/2020-09-28_13-41-55-DgrgzXkj/results/model_best.pth'), ('calibrate', True), ('use_tanh', False), ('normalization_type', 'none')]) for dataset mnist and arch vgg13_inv
Traceback (most recent call last):
  File "policy_attack.py", line 1503, in <module>
    main()
  File "policy_attack.py", line 382, in main
    policy = make_policy_model(args.dataset, args.policy_arch, **kwargs).train().to(device)
  File "/home/pda.pytorch-master/models/__init__.py", line 202, in make_policy_model
    assert osp.exists(weight_fname)
AssertionError
root@149587cc4c1c:/home/pda.pytorch-master#

**Comment by ZiangYan** [comment]
Please read the "Datasets, Victim Models, and Pre-trained Policy Networks" section in README carefully.

**Comment by aspnetcs** [comment]
没有一点线索。
Datasets, Victim Models, and Pre-trained Policy Networks

For the required dataset, victim models, and pre-trained weights of policy networks, please download a tarball at this link and extract it.

After extraction, the data directory should include dataset and victim models for MNIST and CIFAR-10.

For ImageNet dataset, we use the same data format as in the Pytorch official ImageNet example, please put the dataset in data/imagenet.

As described in our paper, we also use ImageNetV2 to provide additional images for ImageNet experiments, please download the ImageNetV2 dataset and then use prepare_imagenet_valv2.py to merge ImageNetV2 with ImageNet.

The tarball also provides initial adversarial examples for targeted attacks (in data directory), and pre-trained policy networks (in output directory).

The structure of data directory should be:

data
├── cifar10
│   └── cifar-10-batches-py
├── cifar10-models
│   ├── carlinet
│   ├── madry_resnet50_l2_1_0
│   └── wrn_28_10_drop
├── imagenet 
│   ├── train
│   ├── val
│   └── valv2
├── init-adv-images-cifar10-test-carlinet.pth
├── init-adv-images-cifar10-test-madry_resnet50_l2_1_0.pth
├── init-adv-images-cifar10-test-wrn_28_10_drop.pth
├── init-adv-images-imagenet-valv2-resnet18.pth
├── init-adv-images-mnist-test-carlinet.pth
├── mnist
│   ├── processed
│   └── raw
└── mnist-models
    └── carlinet
实在不知道怎么做，不知道如何去除那个错误。














--




At 2021-03-25 14:59:53, "yanziang" ***@***.***> wrote:

Please read the "Datasets, Victim Models, and Pre-trained Policy Networks" section in README carefully.
